# Generated by Django 6.1 on 2026-08-19 20:33

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approved_Testers',
            fields=[
                ('mw_id', models.CharField(default='mw-id', max_length=128, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClickInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_id', models.CharField(default='Id not saved', max_length=128)),
                ('task_id', models.CharField(default='id not saved', max_length=32, null=True)),
                ('click_info', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectProfile',
            fields=[
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=32)),
                ('birth_country', django_countries.fields.CountryField(max_length=2)),
                ('residence_country', django_countries.fields.CountryField(max_length=2)),
                ('mother_tongue', models.CharField(default='unknown', max_length=32)),
                ('Do_you_speak_English', models.CharField(default='none', max_length=32)),
                ('participated_before', models.CharField(max_length=32)),
                ('knowledge_on_usability', models.CharField(max_length=32)),
                ('payment_id', models.CharField(default='Id not saved', max_length=128, primary_key=True, serialize=False)),
                ('mw_id', models.CharField(default='mw-id', max_length=32)),
                ('test_status', models.CharField(default='active', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(default='id not saved', max_length=64, null=True)),
                ('task_ans', models.CharField(max_length=1024, null=True)),
                ('test_id', models.CharField(default='Id not saved', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TasksDescription',
            fields=[
                ('task_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('task_description', models.TextField(default='Task description here', null=True)),
                ('task_valid_question', models.TextField(default='Task validation question here', null=True)),
                ('valid_ans_options', models.CharField(default='[]', max_length=128)),
                ('answer', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('subject_id', models.CharField(default='id not saved', max_length=128, primary_key=True, serialize=False)),
                ('task_1_valid_question', models.CharField(max_length=32, null=True)),
                ('task_1_score', models.IntegerField(blank=True, null=True)),
                ('task_1_time', models.IntegerField(blank=True, default=0, null=True)),
                ('task_2_valid_question', models.CharField(max_length=32, null=True)),
                ('task_2_score', models.IntegerField(blank=True, null=True)),
                ('task_2_time', models.IntegerField(blank=True, default=0, null=True)),
                ('test_result', models.CharField(max_length=32, null=True)),
                ('test_rating', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Input',
            fields=[
                ('campaign_id', models.CharField(default='Campaign-Id', max_length=64, primary_key=True, serialize=False)),
                ('secret_key', models.CharField(default='secret-key', max_length=100, null=True)),
                ('application_url', models.CharField(default='url', max_length=100, null=True)),
            ],
        ),
    ]
