# Generated by Django 6.1 on 2026-08-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usabilityTest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approved_testers',
            name='mw_id',
        ),
        migrations.RemoveField(
            model_name='subjectprofile',
            name='mw_id',
        ),
        migrations.RemoveField(
            model_name='test_input',
            name='campaign_id',
        ),
        migrations.AddField(
            model_name='approved_testers',
            name='workerId',
            field=models.CharField(default='worker-default', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='subjectprofile',
            name='groupId',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='subjectprofile',
            name='workerId',
            field=models.CharField(default='worker-default', max_length=32),
        ),
        migrations.AddField(
            model_name='test_input',
            name='campId',
            field=models.CharField(default='camp-default', max_length=64, primary_key=True, serialize=False),
        ),
    ]
