# Generated by Django 6.1 on 2026-08-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usabilityTest', '0002_remove_approved_testers_mw_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved_testers',
            name='workerId',
            field=models.CharField(default='0', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='workerId',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='test_input',
            name='campId',
            field=models.CharField(default='0', max_length=64, primary_key=True, serialize=False),
        ),
    ]
