# Generated by Django 6.1 on 2026-08-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usabilityTest', '0003_alter_approved_testers_workerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectprofile',
            name='campId',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
