# Generated by Django 6.1 on 2026-08-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usabilityTest', '0004_subjectprofile_campid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=256)),
                ('payment_id', models.CharField(max_length=256)),
                ('task_id', models.CharField(max_length=32)),
                ('completada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
    ]
