# Generated by Django 5.1 on 2026-10-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usabilityTest', '0004_subjectprofile_campid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectprofile',
            name='markdown',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
