# Generated by Django 5.1 on 2026-10-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usabilityTest', '0005_subjectprofile_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved_testers',
            name='markdown',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='clickinfo',
            name='markdown',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='markdown',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tasksdescription',
            name='markdown',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='markdown',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='test_input',
            name='markdown',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
