# Generated by Django 6.1 on 2026-09-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usabilityTest', '0005_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='evaluador',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
