# Generated by Django 6.1 on 2026-09-14 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usabilityTest', '0006_evaluacion_evaluador'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='observaciones_generales',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=16)),
                ('finish_time', models.CharField(max_length=16)),
                ('indicador', models.CharField(max_length=16)),
                ('contexto', models.CharField(max_length=64)),
                ('problema', models.TextField(blank=True, default='')),
                ('comentarios', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='usabilityTest.evaluacion')),
            ],
            options={
                'verbose_name': 'Anotacion',
                'verbose_name_plural': 'Anotaciones',
            },
        ),
        migrations.CreateModel(
            name='ProblemaIdentificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('severidad', models.CharField(max_length=32)),
                ('tipo', models.CharField(max_length=32)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='usabilityTest.evaluacion')),
            ],
            options={
                'verbose_name': 'Problema Identificado',
                'verbose_name_plural': 'Problemas Identificados',
            },
        ),
    ]
